name       : python-zope.event
version    : 4.4
release    : 6
source     :
    - https://github.com/zopefoundation/zope.event/archive/4.4.tar.gz : 64a7f9472f5a11b0239270ff40f6854083b3905238a415729067dcfa735856d5
license    : ZPL-2.1
component  : programming.python
summary    : Provides a simple event system
description: |
    Provides a simple event system
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
