name       : python-zope.event
version    : 4.5.0
release    : 8
source     :
    - https://github.com/zopefoundation/zope.event/archive/refs/tags/4.5.0.tar.gz : 36a312ee8f9a75becdc4b58b8602b4e8499872e25fcefdbd2a10d0181a27811b
license    : ZPL-2.1
component  : programming.python
summary    : Provides a simple event system
description: |
    Provides a simple event system
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
