name       : python-zope.event
version    : 4.2.0
release    : 1
source     :
    - https://github.com/zopefoundation/zope.event/archive/4.2.0.tar.gz : 20b0a3abe0dadfac853f9922287e598cce8f73b9dcfd68c10aaf6f897d0dfd7f
license    : ZPL-2.1
component  : programming.python
summary    : Provides a simple event system
description: |
    Provides a simple event system
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install