name       : python-zope.event
version    : 4.3.0
release    : 3
source     :
    - https://github.com/zopefoundation/zope.event/archive/4.3.0.tar.gz : 88d73ba61aab8a3f3114b913c297c8e901173fde4b4754453afa2e859e07bad0
license    : ZPL-2.1
component  : programming.python
summary    : Provides a simple event system
description: |
    Provides a simple event system
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
